services:
  postgres:
    container_name: monetaDatabase
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U developer" ]
      interval: 5s
      retries: 3